### ISSUE TITLE
Whale Version 2.8.108.15 (64-bit) 에서 ReplaceAll 함수의 undefined 문제

### ISSUE THREAD

**Issue by Floodnut** [CASPER-REPSAC/project-manager#18]
ReplaceAll 함수가 동작하지 않습니다.

**Comment by Universe1122** [comment]
웨일 브라우저만의 문제로 판단 됩니다. [참고 링크](https://forum.whale.naver.com/topic/32627/)
일단 replaceAll 함수를 다른걸로 대체 하겠습니다.

**Comment by Universe1122** [comment]
해결 되었습니다.
